name: Bump Releases

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'kubernetes-sigs/kwok' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Update
        env:
          SEND_PR: 'true'
        run: |
          ./hack/supported_releases.sh
